### ISSUE TITLE
Chart 1.6.2 is broken; OCI tag v1.5.0 has not been published

### ISSUE THREAD

**Issue by jhoblitt** [galexrt/extended-ceph-exporter#15] opened 2024-11-07 18:41 UTC
Chart 1.6.2 has the app version set as `v1.5.0` but this tag has not been published:

https://github.com/galexrt/extended-ceph-exporter/blob/main/charts/extended-ceph-exporter/Chart.yaml#L24

https://hub.docker.com/r/galexrt/extended-ceph-exporter/tags

![image](https://github.com/user-attachments/assets/58d1d77a-0435-40cf-9e63-72eb3c2f94b6)

**Comment by galexrt** [comment] 2024-11-08 17:32
To let you know, I am aware of the issue, but haven't been able to come up with a good solution yet.

The problem is that CGO building the extended-ceph-exporter so we are able to use librbd/librados libraries isn't really supported with `promu` (build tool we are using). These libraries are used for `rbd_volumes` extra metrics.
As it stands, I will remove the rados/rbd collector(s) for now till I found a better solution to do multi arch builds.

**Comment by galexrt** [comment] 2024-11-11 22:57
Chat version 1.6.3, and release 1.6.0 has been released with images built https://github.com/galexrt/extended-ceph-exporter/releases/tag/v1.6.0

**Closed by galexrt** 2024-11-11 22:57 UTC
